package com.ecom.enumType;

public enum CategoryType {
	
	MOBILES,COMPUTERS,SHIRTS,PANTS,TSHIRTS,SHORTS,BOOKS,HOME,KITCHEN,DECORATION,ELECTRONICS,BEAUTY,HEALTH,GROCERY,SPORTS,BAGS,
	MOVIES,SONGS,CARS,BIKES,MENSFASHION,LADIESFASHION,BOYS,GIRLS,KIDS

}
